version: "3.8"
services:
  api:
    image: davidsongomes/evolution-api:v1.4.8
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [ node.role == manager ]
    volumes:
      - evolution_instances_data:/evolution/instances
      - evolution_store_data:/evolution/store
    networks:
      - nlb_ingress
    environment:
      SERVER_URL: ${SERVER_URL}
      CORS_ORIGIN: ${CORS_ORIGIN}
      CORS_METHODS: ${CORS_METHODS}
      CORS_CREDENTIALS: ${CORS_CREDENTIALS}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_COLOR: ${LOG_COLOR}
      LOG_BAILEYS: ${LOG_BAILEYS}
      DEL_INSTANCE: ${DEL_INSTANCE}
      STORE_MESSAGES: ${STORE_MESSAGES}
      STORE_MESSAGE_UP: ${STORE_MESSAGE_UP}
      STORE_CONTACTS: ${STORE_CONTACTS}
      STORE_CHATS: ${STORE_CHATS}
      CLEAN_STORE_CLEANING_INTERVAL: ${CLEAN_STORE_CLEANING_INTERVAL}
      CLEAN_STORE_MESSAGES: ${CLEAN_STORE_MESSAGES}
      CLEAN_STORE_MESSAGE_UP: ${CLEAN_STORE_MESSAGE_UP}
      CLEAN_STORE_CONTACTS: ${CLEAN_STORE_CONTACTS}
      CLEAN_STORE_CHATS: ${CLEAN_STORE_CHATS}
      DATABASE_ENABLED: ${DATABASE_ENABLED}
      WEBHOOK_GLOBAL_ENABLED: ${WEBHOOK_GLOBAL_ENABLED}
      WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS: ${WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS}
      WEBHOOK_EVENTS_APPLICATION_STARTUP: ${WEBHOOK_EVENTS_APPLICATION_STARTUP}
      WEBHOOK_EVENTS_QRCODE_UPDATED: ${WEBHOOK_EVENTS_QRCODE_UPDATED}
      WEBHOOK_EVENTS_MESSAGES_SET: ${WEBHOOK_EVENTS_MESSAGES_SET}
      WEBHOOK_EVENTS_MESSAGES_UPSERT: ${WEBHOOK_EVENTS_MESSAGES_UPSERT}
      WEBHOOK_EVENTS_MESSAGES_UPDATE: ${WEBHOOK_EVENTS_MESSAGES_UPDATE}
      WEBHOOK_EVENTS_MESSAGES_DELETE: ${WEBHOOK_EVENTS_MESSAGES_DELETE}
      WEBHOOK_EVENTS_SEND_MESSAGE: ${WEBHOOK_EVENTS_SEND_MESSAGE}
      WEBHOOK_EVENTS_CONTACTS_SET: ${WEBHOOK_EVENTS_CONTACTS_SET}
      WEBHOOK_EVENTS_CONTACTS_UPSERT: ${WEBHOOK_EVENTS_CONTACTS_UPSERT}
      WEBHOOK_EVENTS_CONTACTS_UPDATE: ${WEBHOOK_EVENTS_CONTACTS_UPDATE}
      WEBHOOK_EVENTS_PRESENCE_UPDATE: ${WEBHOOK_EVENTS_PRESENCE_UPDATE}
      WEBHOOK_EVENTS_CHATS_SET: ${WEBHOOK_EVENTS_CHATS_SET}
      WEBHOOK_EVENTS_CHATS_UPSERT: ${WEBHOOK_EVENTS_CHATS_UPSERT}
      WEBHOOK_EVENTS_CHATS_UPDATE: ${WEBHOOK_EVENTS_CHATS_UPDATE}
      WEBHOOK_EVENTS_CHATS_DELETE: ${WEBHOOK_EVENTS_CHATS_DELETE}
      WEBHOOK_EVENTS_GROUPS_UPSERT: ${WEBHOOK_EVENTS_GROUPS_UPSERT}
      WEBHOOK_EVENTS_GROUPS_UPDATE: ${WEBHOOK_EVENTS_GROUPS_UPDATE}
      WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE: ${WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE}
      WEBHOOK_EVENTS_CONNECTION_UPDATE: ${WEBHOOK_EVENTS_CONNECTION_UPDATE}
      WEBHOOK_EVENTS_CALL: ${WEBHOOK_EVENTS_CALL}
      WEBHOOK_EVENTS_NEW_JWT_TOKEN: ${WEBHOOK_EVENTS_NEW_JWT_TOKEN}
      CONFIG_SESSION_PHONE_CLIENT: ${CONFIG_SESSION_PHONE_CLIENT}
      CONFIG_SESSION_PHONE_NAME: ${CONFIG_SESSION_PHONE_NAME}
      QRCODE_LIMIT: ${QRCODE_LIMIT}
      AUTHENTICATION_TYPE: ${AUTHENTICATION_TYPE}
      AUTHENTICATION_API_KEY: ${AUTHENTICATION_API_KEY}
      AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: ${AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES}
    command: ['node', './dist/src/main.js']

volumes:
  evolution_instances_data:
  evolution_store_data:

networks:
  nlb_ingress:
    external: true
